[package]
name = "xterm-server"
version = "0.1.0"
edition = "2021"


[dependencies]
nix = {version = "0.28.0", features = ["term", "process", "fs"]}
websocket = "0.24.0"
log = "0.4.14"
env_logger = "0.10.0"

